"use strict";

const ERROR_CODES = {
  INVALID_PAYLOAD: "INVALID_PAYLOAD",
  ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
  ROOM_EXPIRED: "ROOM_EXPIRED",
  ROOM_FULL: "ROOM_FULL",
  ROOM_NOT_JOINABLE: "ROOM_NOT_JOINABLE",
  NOT_ROOM_MEMBER: "NOT_ROOM_MEMBER",
  NOT_ROOM_HOST: "NOT_ROOM_HOST",
  INVALID_PLAYER_COUNT: "INVALID_PLAYER_COUNT",
  NOT_ALL_READY: "NOT_ALL_READY",
  GAME_NOT_STARTED: "GAME_NOT_STARTED",
  GAME_ALREADY_STARTED: "GAME_ALREADY_STARTED",
  GAME_ALREADY_ENDED: "GAME_ALREADY_ENDED",
  PHASE_MISMATCH: "PHASE_MISMATCH",
  VERSION_CONFLICT: "VERSION_CONFLICT",
  DUPLICATE_COMMAND: "DUPLICATE_COMMAND",
  NOT_CURRENT_ACTOR: "NOT_CURRENT_ACTOR",
  INVALID_TARGET: "INVALID_TARGET",
  TARGET_ALREADY_DEAD: "TARGET_ALREADY_DEAD",
  TARGET_ALREADY_INVESTIGATED: "TARGET_ALREADY_INVESTIGATED",
  ACTION_NOT_ALLOWED: "ACTION_NOT_ALLOWED",
  INTERNAL_ERROR: "INTERNAL_ERROR"
};

const RETRYABLE_CODES = new Set([
  ERROR_CODES.VERSION_CONFLICT,
  ERROR_CODES.INTERNAL_ERROR
]);

module.exports = {
  ERROR_CODES,
  RETRYABLE_CODES
};
