const EXECUTIVE_COMMAND_TYPES = ["EXEC_INVESTIGATE", "EXEC_SPECIAL_ELECTION", "EXEC_POLICY_PEEK_ACK", "EXECUTE_PLAYER"];
const TARGET_EXECUTIVE_COMMAND_TYPES = ["EXEC_INVESTIGATE", "EXEC_SPECIAL_ELECTION", "EXECUTE_PLAYER"];
const POLICY_PICK_TASK_TYPES = ["PRESIDENT_DISCARD_POLICY", "CHANCELLOR_ENACT_POLICY"];

const REFRESH_AFTER_COMMAND_ERROR_CODES = [
  "VERSION_CONFLICT",
  "PHASE_MISMATCH",
  "DUPLICATE_COMMAND",
  "ALREADY_ACTED",
  "FORBIDDEN",
  "ACTION_NOT_ALLOWED",
  "NOT_CURRENT_ACTOR",
  "INVALID_TARGET",
  "TARGET_ALREADY_DEAD",
  "TARGET_ALREADY_INVESTIGATED",
];

module.exports = {
  EXECUTIVE_COMMAND_TYPES,
  TARGET_EXECUTIVE_COMMAND_TYPES,
  POLICY_PICK_TASK_TYPES,
  REFRESH_AFTER_COMMAND_ERROR_CODES,
};
