"use strict";

const MIN_PLAYER_COUNT = 5;
const MAX_PLAYER_COUNT = 10;
const ROOM_CODE_LENGTH = 6;
const ROOM_CODE_RETRY_LIMIT = 10;
const MAX_DISPLAY_NAME_LENGTH = 20;
const ROOM_TTL_LOBBY_MS = 2 * 60 * 60 * 1000;
const ROOM_TTL_ACTIVE_MS = 12 * 60 * 60 * 1000;
const ROOM_TTL_RESULT_MS = 24 * 60 * 60 * 1000;
const COMMAND_RECORD_TTL_MS = 24 * 60 * 60 * 1000;

const ROLE_PRESET_BY_PLAYER_COUNT = {
  5: ["LIBERAL", "LIBERAL", "LIBERAL", "FASCIST", "HITLER"],
  6: ["LIBERAL", "LIBERAL", "LIBERAL", "LIBERAL", "FASCIST", "HITLER"],
  7: ["LIBERAL", "LIBERAL", "LIBERAL", "LIBERAL", "FASCIST", "FASCIST", "HITLER"],
  8: ["LIBERAL", "LIBERAL", "LIBERAL", "LIBERAL", "LIBERAL", "FASCIST", "FASCIST", "HITLER"],
  9: ["LIBERAL", "LIBERAL", "LIBERAL", "LIBERAL", "LIBERAL", "FASCIST", "FASCIST", "FASCIST", "HITLER"],
  10: ["LIBERAL", "LIBERAL", "LIBERAL", "LIBERAL", "LIBERAL", "LIBERAL", "FASCIST", "FASCIST", "FASCIST", "HITLER"]
};

const EXECUTIVE_POWER_TRACK = {
  5: { 3: "POLICY_PEEK", 4: "EXECUTION", 5: "EXECUTION" },
  6: { 3: "POLICY_PEEK", 4: "EXECUTION", 5: "EXECUTION" },
  7: { 2: "INVESTIGATE", 3: "SPECIAL_ELECTION", 4: "EXECUTION", 5: "EXECUTION" },
  8: { 2: "INVESTIGATE", 3: "SPECIAL_ELECTION", 4: "EXECUTION", 5: "EXECUTION" },
  9: { 1: "INVESTIGATE", 2: "INVESTIGATE", 3: "SPECIAL_ELECTION", 4: "EXECUTION", 5: "EXECUTION" },
  10: { 1: "INVESTIGATE", 2: "INVESTIGATE", 3: "SPECIAL_ELECTION", 4: "EXECUTION", 5: "EXECUTION" }
};

const INITIAL_POLICY_DECK = [
  "LIBERAL", "LIBERAL", "LIBERAL", "LIBERAL", "LIBERAL", "LIBERAL",
  "FASCIST", "FASCIST", "FASCIST", "FASCIST", "FASCIST", "FASCIST",
  "FASCIST", "FASCIST", "FASCIST", "FASCIST", "FASCIST"
];

const PHASES = {
  ROLE_REVEAL: "role_reveal",
  NOMINATION: "nomination",
  VOTING: "voting",
  HITLER_CHECK: "hitler_check",
  LEGISLATIVE_PRESIDENT: "legislative_president",
  LEGISLATIVE_CHANCELLOR: "legislative_chancellor",
  VETO_RESPONSE: "veto_response",
  EXECUTIVE_ACTION: "executive_action",
  ROUND_RESULT: "round_result",
  GAME_ENDED: "game_ended"
};

const COMMAND_TYPES = {
  ACK_ROLE_REVEAL: "ACK_ROLE_REVEAL",
  NOMINATE_CHANCELLOR: "NOMINATE_CHANCELLOR",
  SUBMIT_VOTE: "SUBMIT_VOTE",
  PRESIDENT_DISCARD_POLICY: "PRESIDENT_DISCARD_POLICY",
  CHANCELLOR_ENACT_POLICY: "CHANCELLOR_ENACT_POLICY",
  CHANCELLOR_REQUEST_VETO: "CHANCELLOR_REQUEST_VETO",
  PRESIDENT_RESPOND_VETO: "PRESIDENT_RESPOND_VETO",
  EXEC_INVESTIGATE: "EXEC_INVESTIGATE",
  EXEC_SPECIAL_ELECTION: "EXEC_SPECIAL_ELECTION",
  EXEC_POLICY_PEEK_ACK: "EXEC_POLICY_PEEK_ACK",
  EXECUTE_PLAYER: "EXECUTE_PLAYER"
};

const WIN_REASONS = {
  LIBERAL_FIVE_POLICIES: "LIBERAL_FIVE_POLICIES",
  FASCIST_SIX_POLICIES: "FASCIST_SIX_POLICIES",
  HITLER_ELECTED_CHANCELLOR: "HITLER_ELECTED_CHANCELLOR",
  HITLER_EXECUTED: "HITLER_EXECUTED"
};

module.exports = {
  COMMAND_RECORD_TTL_MS,
  COMMAND_TYPES,
  EXECUTIVE_POWER_TRACK,
  INITIAL_POLICY_DECK,
  MAX_DISPLAY_NAME_LENGTH,
  MAX_PLAYER_COUNT,
  MIN_PLAYER_COUNT,
  PHASES,
  ROLE_PRESET_BY_PLAYER_COUNT,
  ROOM_CODE_LENGTH,
  ROOM_CODE_RETRY_LIMIT,
  ROOM_TTL_ACTIVE_MS,
  ROOM_TTL_LOBBY_MS,
  ROOM_TTL_RESULT_MS,
  WIN_REASONS
};
