const ROOM_STATUS = {
  LOBBY: 'lobby',
  IN_GAME: 'in_game',
  ENDED: 'ended',
  EXPIRED: 'expired',
};

const ROUTE_HINT = {
  LOBBY: 'lobby',
  IDENTITY: 'identity',
  BOARD: 'board',
  RESULT: 'result',
  HOME: 'home',
};

const PHASE = {
  ROLE_REVEAL: 'role_reveal',
  NOMINATION: 'nomination',
  VOTING: 'voting',
  HITLER_CHECK: 'hitler_check',
  LEGISLATIVE_PRESIDENT: 'legislative_president',
  LEGISLATIVE_CHANCELLOR: 'legislative_chancellor',
  VETO_RESPONSE: 'veto_response',
  EXECUTIVE_ACTION: 'executive_action',
  ROUND_RESULT: 'round_result',
  GAME_ENDED: 'game_ended',
};

const VOTE = {
  JA: 'JA',
  NEIN: 'NEIN',
};

const POLICY_TYPE = {
  LIBERAL: 'LIBERAL',
  FASCIST: 'FASCIST',
};

const TASK_TYPE = {
  ACK_ROLE_REVEAL: 'ACK_ROLE_REVEAL',
  NOMINATE_CHANCELLOR: 'NOMINATE_CHANCELLOR',
  SUBMIT_VOTE: 'SUBMIT_VOTE',
  PRESIDENT_DISCARD_POLICY: 'PRESIDENT_DISCARD_POLICY',
  CHANCELLOR_ENACT_POLICY: 'CHANCELLOR_ENACT_POLICY',
  CHANCELLOR_REQUEST_VETO: 'CHANCELLOR_REQUEST_VETO',
  PRESIDENT_RESPOND_VETO: 'PRESIDENT_RESPOND_VETO',
  EXEC_INVESTIGATE: 'EXEC_INVESTIGATE',
  EXEC_SPECIAL_ELECTION: 'EXEC_SPECIAL_ELECTION',
  EXEC_POLICY_PEEK_ACK: 'EXEC_POLICY_PEEK_ACK',
  EXECUTE_PLAYER: 'EXECUTE_PLAYER',
};

const COMMAND_TYPE = TASK_TYPE;

const ERROR_CODE = {
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_EXPIRED: 'ROOM_EXPIRED',
  ROOM_FULL: 'ROOM_FULL',
  ROOM_NOT_JOINABLE: 'ROOM_NOT_JOINABLE',
  NOT_ROOM_MEMBER: 'NOT_ROOM_MEMBER',
  NOT_ROOM_HOST: 'NOT_ROOM_HOST',
  INVALID_PLAYER_COUNT: 'INVALID_PLAYER_COUNT',
  NOT_ALL_READY: 'NOT_ALL_READY',
  GAME_NOT_STARTED: 'GAME_NOT_STARTED',
  GAME_ALREADY_STARTED: 'GAME_ALREADY_STARTED',
  GAME_ALREADY_ENDED: 'GAME_ALREADY_ENDED',
  PHASE_MISMATCH: 'PHASE_MISMATCH',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  DUPLICATE_COMMAND: 'DUPLICATE_COMMAND',
  NOT_CURRENT_ACTOR: 'NOT_CURRENT_ACTOR',
  INVALID_TARGET: 'INVALID_TARGET',
  TARGET_ALREADY_DEAD: 'TARGET_ALREADY_DEAD',
  TARGET_ALREADY_INVESTIGATED: 'TARGET_ALREADY_INVESTIGATED',
  ACTION_NOT_ALLOWED: 'ACTION_NOT_ALLOWED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

const APP_EVENT = {
  APP_HIDDEN: 'APP_HIDDEN',
  APP_FOREGROUND: 'APP_FOREGROUND',
  SNAPSHOT_UPDATED: 'SNAPSHOT_UPDATED',
  ROOM_CHANGED: 'ROOM_CHANGED',
};

const STORAGE_KEYS = {
  SESSION: 'secret_hitler_session',
  DISPLAY_NAME: 'secret_hitler_display_name',
  ACTIVE_ROOM_ID: 'secret_hitler_active_room_id',
  ACTIVE_ROOM_CODE: 'secret_hitler_active_room_code',
  ACTIVE_MEMBER_ID: 'secret_hitler_active_member_id',
  ACTIVE_ROOM_STATUS: 'secret_hitler_active_room_status',
  LAST_RECOVER_AT: 'secret_hitler_last_recover_at',
};

module.exports = {
  ROOM_STATUS,
  ROUTE_HINT,
  PHASE,
  VOTE,
  POLICY_TYPE,
  TASK_TYPE,
  COMMAND_TYPE,
  ERROR_CODE,
  APP_EVENT,
  STORAGE_KEYS,
};

